In [1]:
#ejercicio 1. Escriba un programa NumPy para obtener la versión numpy y mostrar la configuración de compilación numpy
import numpy as np
print(np.__version__)
print(np.show_config())

1.23.1
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [1]:
#ejercicio 2. Escriba un programa NumPy para obtener ayuda sobre la función de agregar.
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [2]:
#ejercicio 3. Escriba un programa NumPy para probar si ninguno de los elementos de una matriz dada es cero.
import numpy as np
a=np.random.randint(20, size=(3, 4))
print("matriz original:")
print(a)
print("Prueba si ninguno de los elementos de dicha matriz es cero:")
print(np.all(a))

matriz original:
[[14 10 11 13]
 [ 1 13 11  5]
 [ 8  6 15  5]]
Prueba si ninguno de los elementos de dicha matriz es cero:
True


In [3]:
#ejercicio 4. Escriba un programa NumPy para probar si alguno de los elementos de una matriz dada es distinto de cero.
import numpy as np
x = np.array([1, 0, 0, 0])
print("matriz original:")
print(x)
print("Pruebe si alguno de los elementos de una matriz dada es distinto de cero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("matriz original:")
print(x)
print("Pruebe si alguno de los elementos de una matriz dada es distinto de cero:")
print(np.any(x))

matriz original:
[1 0 0 0]
Pruebe si alguno de los elementos de una matriz dada es distinto de cero:
True
matriz original:
[0 0 0 0]
Pruebe si alguno de los elementos de una matriz dada es distinto de cero:
False


In [4]:
#ejercicio 5. Escriba un programa NumPy para probar una matriz dada en cuanto a elementos 
#para la finitud (no infinito o no un número).
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("matriz original:")
print(a)
print("Pruebe la finitud de una matriz dada por elementos:")
print(np.isfinite(a))

matriz original:
[ 1.  0. nan inf]
Pruebe la finitud de una matriz dada por elementos:
[ True  True False False]


In [5]:
#ejercicio 6. Escriba un programa NumPy para probar el infinito positivo o negativo en cuanto a elementos.
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("matriz original:")
print(a)
print("Pruebe elementos sabios para infinito positivo o negativo:")
print(np.isinf(a))

matriz original:
[ 1.  0. nan inf]
Pruebe elementos sabios para infinito positivo o negativo:
[False False False  True]


In [6]:
#ejercicio 7. Escriba un programa NumPy para probar el NaN de una matriz determinada en cuanto a elementos.
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("matriz original:")
print(a)
print("Pruebe los elementos para NaN:")
print(np.isnan(a))

matriz original:
[ 1.  0. nan inf]
Pruebe los elementos para NaN:
[False False  True False]


In [8]:
#ejercicio 8. Escriba un programa NumPy para probar en cuanto a elementos el número complejo, 
#el número real de una matriz dada. También pruebe si un número dado es de tipo escalar o no.
import numpy as np
a = np.array([1+4j, 1+0j, 4.5, 8, 2, 1j])
print("matriz original:")
print(a)
print("Comprobación de número complejo:")
print(np.iscomplex(a))
print("Comprobación de número real:")
print(np.isreal(a))
print("Comprobando el tipo escalar:")
print(np.isscalar(2))
print(np.isscalar([2]))

matriz original:
[1. +4.j 1. +0.j 4.5+0.j 8. +0.j 2. +0.j 0. +1.j]
Comprobación de número complejo:
[ True False False False False  True]
Comprobación de número real:
[False  True  True  True  True False]
Comprobando el tipo escalar:
True
False


In [9]:
#ejercicio 9. Escriba un programa NumPy para probar si dos matrices son iguales a elementos dentro de una tolerancia.
import numpy as np
print("Pruebe si dos matrices son iguales en cuanto a elementos dentro de una tolerancia:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Pruebe si dos matrices son iguales en cuanto a elementos dentro de una tolerancia:
False
True
False
False
True


In [10]:
#ejercicio 10. Escriba un programa NumPy para crear una comparación de elementos (mayor, mayor_igual, menor y menor_igual)
# de dos matrices dadas.
import numpy as np
x = np.array([4, 5])
y = np.array([2, 5])
print("Números originales:")
print(x)
print(y)
print("Comparación mayor")
print(np.greater(x, y))
print("Comparación mayor igual")
print(np.greater_equal(x, y))
print("Comparación menor")
print(np.less(x, y))
print("Comparación menor igual")
print(np.less_equal(x, y))

Números originales:
[3 5]
[2 5]
Comparación mayor
[ True False]
Comparación mayor igual
[ True  True]
Comparación menor
[False False]
Comparación menor igual
[False  True]


In [13]:
#ejercicio 11. Escriba un programa NumPy para crear una comparación de elementos (igual, igual dentro de una tolerancia)
# de dos matrices dadas.
import numpy as np
x = np.array([2, 79, 85, 34, 150, -135, 120, -10, 60, 100])
y = np.array([2, 79, 85, 34, 150, -135, 120, -10, 60, 100.0001])
print("Números originales:")
print(x)
print(y)
print("Comparando si es igual:")
print(np.equal(x, y))
print("Comparando si es igual dentro de una tolerancia:")
print(np.allclose(x, y))

Números originales:
[   2   79   85   34  150 -135  120  -10   60  100]
[   2.       79.       85.       34.      150.     -135.      120.
  -10.       60.      100.0001]
Comparando si es igual:
[ True  True  True  True  True  True  True  True  True False]
Comparando si es igual dentro de una tolerancia:
True


In [14]:
#ejercicio 12 Escriba un programa NumPy para crear una matriz con los valores 1, 7, 13, 105.
# y determine el tamaño de la memoria ocupada por la matriz
import numpy as np
X = np.array([1, 7, 13, 105])
print("Matriz original:")
print(X)
print("Tamaño de la memoria ocupada por dicha matriz")
print("%d bytes" % (X.size * X.itemsize))

Matriz original:
[  1   7  13 105]
Tamaño de la memoria ocupada por dicha matriz
16 bytes


In [15]:
#ejercicio 13. Escriba un programa NumPy para crear una matriz de 10 ceros, 10 unos, 10 cincos.
import numpy as np
array=np.zeros(10)
print("Una matriz de 10 ceros:")
print(array)
array=np.ones(10)
print("Una matriz de 10 unos:")
print(array)
array=np.ones(10)*5
print("Una matriz de 10 cincos:")
print(array)

Una matriz de 10 ceros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Una matriz de 10 unos:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Una matriz de 10 cincos:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
#ejercicio 14. Escriba un programa NumPy para crear una matriz de números enteros del 30 al 70.
import numpy as np
array=np.arange(30,71)
print("Matriz de los enteros de 30 a 70")
print(array)

Matriz de los enteros de 30 a 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [17]:
#ejercicio 15. Escriba un programa NumPy para crear una matriz de todos los enteros pares del 30 al 70.
import numpy as np
array=np.arange(30,71,2)
print("Matriz de todos los enteros pares del 30 al 70")
print(array)

Matriz de todos los enteros pares del 30 al 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [19]:
#ejercicio 16. Escriba un programa NumPy para crear una matriz de identidad de 3x3
import numpy as np
array2D=np.identity(3)
print('matriz 3x3:')
print(array2D)

matriz 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#ejercicio 17. Escriba un programa NumPy para generar un número aleatorio entre 0 y 1.
import numpy as np
rand_num = np.random.normal(0,1,1)
print("Número aleatorio entre 0 y 1:")
print(rand_num)

Número aleatorio entre 0 y 1:
[0.04542748]


In [21]:
#ejercicio 18. Escriba un programa NumPy para generar una matriz de 15 números aleatorios 
#a partir de una distribución normal estándar.
import numpy as np
rand_num = np.random.normal(0,1,15)
print("15 números aleatorios de una distribución normal estándar:")
print(rand_num)

15 números aleatorios de una distribución normal estándar:
[ 1.61016368 -0.34619423  0.37611875  1.12530808  0.84879271 -0.28518702
  0.62949279  1.1651849   1.23240937 -0.41701684 -0.49118365 -1.75758188
 -0.07169907  1.6610131   0.07275637]


In [22]:
#ejercicio 19. Escriba un programa NumPy para crear un vector con valores que oscilen entre 15 y 55.
#e imprima todos los valores excepto el primero y el último
import numpy as np
v = np.arange(15,55)
print("vector Original:")
print(v)
print("Todos los valores excepto el primero y el último de dicho vector:")
print(v[1:-1])

vector Original:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
Todos los valores excepto el primero y el último de dicho vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [23]:
#ejercicio 20. Escriba un programa NumPy para crear una matriz de 3X4 usándola e itera sobre ella
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Matriz Original:")
print(a)
print("Cada elemento de la matriz es:")
for x in np.nditer(a):
  print(x,end=" ")

Matriz Original:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Cada elemento de la matriz es:
10 11 12 13 14 15 16 17 18 19 20 21 

In [25]:
#ejercicio 21. Escriba un programa NumPy para crear un vector de longitud 10 
#con valores distribuidos uniformemente entre 5 y 50.
import numpy as np
v = np.linspace(5, 49, 10)
print("Longitud 10 con valores distribuidos uniformemente entre 5 y 50:")
print(v)

Longitud 10 con valores distribuidos uniformemente entre 5 y 50:
[ 5.          9.88888889 14.77777778 19.66666667 24.55555556 29.44444444
 34.33333333 39.22222222 44.11111111 49.        ]


In [26]:
#ejercicio 22. Escriba un programa NumPy para crear un vector con valores de 0 a 20 
#y cambie el signo de los números en el rango de 9 a 15.
import numpy as np
x = np.arange(21)
print("vector Original:")
print(x)
print("cambiar el signo de los números en el rango de 9 a 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

vector Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
cambiar el signo de los números en el rango de 9 a 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [27]:
#ejercicio 23. Escriba un programa NumPy para crear un vector de longitud 5 lleno de números enteros arbitrarios del 0 al 10.
import numpy as np
x = np.random.randint(0, 11, 5)
print("Vector de longitud 5 lleno de números enteros arbitrarios de 0 a 10:")
print(x)

Vector de longitud 5 lleno de números enteros arbitrarios de 0 a 10:
[0 5 8 7 3]


In [28]:
#ejercicio 24. Escriba un programa NumPy para multiplicar los valores de dos vectores dados.
import numpy as np
x = np.array([1, 4, 3, 9])
print("Vector1")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector2")
print(y)
result = x * y
print("Multiplica los valores de dos de dichos vectores:")
print(result)

Vector1
[1 4 3 9]
Vector2
[3 1 3 0]
Multiplica los valores de dos de dichos vectores:
[3 4 9 0]


In [29]:
#ejercicio 25. Escriba un programa NumPy para crear una matriz de 3x4 llena de valores del 10 al 21
import numpy as np
matriz= np.arange(10,22).reshape((3, 4))
print(matriz)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
